# Site Settings
title: Aditya Volety - Curriculum Vitae
url: 'http://adityavolety.com'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Aditya Volety
tagline: Informatica, Unix, Big data Engineer and Business Intelligence
pic: yogesh.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am a Database Engineer and working on  Greenplum Database and PostgreSQL Database Server at Epsilon India. Currently living in Hyderabad, India. Previously I have worked as Greenplum, MarkLogic database administrator in Broadridge financial Solutions and Greenplum Database/DCA Support Engineer in Wipro Technologies for Pivotal Inc. My interests range from technology to travel. I am also interested in reading,blogging and listening to music. And I always try to be better version of myself.'

#sidebar links
email: vaditya826@gmail.com
phone: +91-8143169188
website: adityavolety.com #do not add http://
linkedin: Aditya-vvs
github: adityavolety
twitter: '@pradivvs'
#Update all the sections by editing the files inside _data folder.


# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
